// Define the type for the categories
type CategoryType = {
  [key: string]: {
    [key: string]: string[];
  };
};

// Define the categories object
const categories: CategoryType = {
  en: {
    'Sports Nutrition': [
      'protein shakes',
      'oatmeal',
      'chicken breast',
      'bananas',
      'buckwheat',
      'nuts',
      'fish (salmon, tuna)',
    ],
    'Diet Nutrition': [
      'salads',
      'lean proteins',
      'vegetables',
      'fruits',
      'yogurts',
      'cottage cheese',
      'buckwheat',
    ],
    'Vegetarian Nutrition': [
      'tofu',
      'avocado',
      'quinoa',
      'green smoothies',
      'chickpeas',
      'soybeans',
      'eggplants',
      'zucchini',
    ],
    'Vegan Nutrition': [
      'plant milk',
      'nut butters',
      'tofu',
      'seitan',
      'beans',
      'vegetable soups',
      'fruits',
      'nuts',
    ],
    'Keto Nutrition': [
      'eggs',
      'fatty meats',
      'cheese',
      'butter',
      'avocado',
      'keto desserts',
      'olive oil',
      'fish',
    ],
    'Paleo Nutrition': [
      'meat',
      'fish',
      'vegetables',
      'fruits',
      'nuts',
      'seeds',
      'olive oil',
      'sweet potatoes',
    ],
    'Balanced Nutrition': [
      'whole grain products',
      'chicken',
      'fish',
      'vegetables',
      'fruits',
      'yogurts',
      'eggs',
      'plant oils',
    ],
    'Gluten-Free Nutrition': [
      'rice',
      'buckwheat',
      'corn flour',
      'vegetables',
      'fruits',
      'meat',
      'fish',
      'gluten-free pasta',
    ],
    'Low-Carb Nutrition': [
      'eggs',
      'chicken breast',
      'fish',
      'low-carb vegetables (broccoli, cauliflower)',
      'cheese',
      'avocado',
      'nuts',
      'olive oil',
    ],
    'Mediterranean Diet': [
      'olive oil',
      'fish',
      'seafood',
      'vegetables',
      'fruits',
      'whole grain products',
      'Greek yogurt',
      'wine (in moderation)',
    ],
  },
  ru: {
    'Спортивное питание': [
      'белковые коктейли',
      'овсянка',
      'куриная грудка',
      'бананы',
      'гречка',
      'орехи',
      'рыба (лосось, тунец)',
    ],
    'Диетическое питание': [
      'салаты',
      'нежирные белки',
      'овощи',
      'фрукты',
      'йогурты',
      'творог',
      'гречка',
    ],
    'Вегетарианское питание': [
      'тофу',
      'авокадо',
      'киноа',
      'зелёные смузи',
      'нут',
      'соя',
      'баклажаны',
      'цуккини',
    ],
    'Веганское питание': [
      'растительное молоко',
      'ореховые пасты',
      'тофу',
      'сейтан',
      'бобы',
      'овощные супы',
      'фрукты',
      'орехи',
    ],
    'Кето питание': [
      'яйца',
      'жирное мясо',
      'сыр',
      'сливочное масло',
      'авокадо',
      'кето-десерты',
      'оливковое масло',
      'рыба',
    ],
    'Палео питание': [
      'мясо',
      'рыба',
      'овощи',
      'фрукты',
      'орехи',
      'семена',
      'оливковое масло',
      'сладкий картофель',
    ],
    'Сбалансированное питание': [
      'цельнозерновые продукты',
      'курица',
      'рыба',
      'овощи',
      'фрукты',
      'йогурты',
      'яйца',
      'растительные масла',
    ],
    'Безглютеновое питание': [
      'рис',
      'гречка',
      'кукурузная мука',
      'овощи',
      'фрукты',
      'мясо',
      'рыба',
      'безглютеновая паста',
    ],
    'Низкоуглеводное питание': [
      'яйца',
      'куриная грудка',
      'рыба',
      'овощи с низким содержанием углеводов (брокколи, цветная капуста)',
      'сыр',
      'авокадо',
      'орехи',
      'оливковое масло',
    ],
    'Средиземноморская диета': [
      'оливковое масло',
      'рыба',
      'морепродукты',
      'овощи',
      'фрукты',
      'цельнозерновые продукты',
      'греческий йогурт',
      'вино (в умеренных количествах)',
    ],
  },
  tr: {
    'Spor Beslenmesi': [
      'protein shakes',
      'yulaf ezmesi',
      'tavuk göğsü',
      'muz',
      'karabuğday',
      'kuruyemiş',
      'balık (somon, ton)',
    ],
    'Diyet Beslenmesi': [
      'salatalar',
      'yağsız proteinler',
      'sebzeler',
      'meyveler',
      'yoğurtlar',
      'çökelek',
      'karabuğday',
    ],
    'Vejetaryen Beslenme': [
      'tofu',
      'avokado',
      'kinoa',
      'yeşil smoothieler',
      'nohut',
      'soya',
      'patlıcan',
      'kabak',
    ],
    'Vegan Beslenme': [
      'bitki sütü',
      'fındık ezmeleri',
      'tofu',
      'seitan',
      'fasulye',
      'sebze çorbaları',
      'meyveler',
      'kuruyemiş',
    ],
    'Keto Beslenme': [
      'yumurta',
      'yağlı etler',
      'peynir',
      'tereyağı',
      'avokado',
      'keto tatlıları',
      'zeytinyağı',
      'balık',
    ],
    'Paleo Beslenme': [
      'et',
      'balık',
      'sebzeler',
      'meyveler',
      'kuruyemiş',
      'tohumlar',
      'zeytinyağı',
      'tatlı patates',
    ],
    'Dengeli Beslenme': [
      'tam tahıllı ürünler',
      'tavuk',
      'balık',
      'sebzeler',
      'meyveler',
      'yoğurtlar',
      'yumurta',
      'bitkisel yağlar',
    ],
    'Glutensiz Beslenme': [
      'pirinç',
      'karabuğday',
      'mısır unu',
      'sebzeler',
      'meyveler',
      'et',
      'balık',
      'glutensiz makarna',
    ],
    'Düşük Karbonhidratlı Beslenme': [
      'yumurta',
      'tavuk göğsü',
      'balık',
      'düşük karbonhidratlı sebzeler (brokoli, karnabahar)',
      'peynir',
      'avokado',
      'kuruyemiş',
      'zeytinyağı',
    ],
    'Akdeniz Diyeti': [
      'zeytinyağı',
      'balık',
      'deniz ürünleri',
      'sebzeler',
      'meyveler',
      'tam tahıllı ürünler',
      'Yunan yoğurdu',
      'şarap (ölçülü miktarda)',
    ],
  },
  ar: {
    'التغذية الرياضية': [
      'بروتين شيك',
      'دقيق الشوفان',
      'صدر الدجاج',
      'الموز',
      'الحنطة السوداء',
      'المكسرات',
      'السمك (السلمون، التونة)',
    ],
    'التغذية الغذائية': [
      'سلطات',
      'بروتينات خالية من الدهون',
      'خضروات',
      'فواكه',
      'زبادي',
      'جبن قريش',
      'الحنطة السوداء',
    ],
    'التغذية النباتية': [
      'توفو',
      'أفوكادو',
      'الكينوا',
      'العصائر الخضراء',
      'الحمص',
      'الصويا',
      'الباذنجان',
      'الكوسة',
    ],
    'التغذية النباتية الصرفة': [
      'حليب نباتي',
      'زبدة المكسرات',
      'توفو',
      'سيتان',
      'فول',
      'شوربة الخضار',
      'فواكه',
      'مكسرات',
    ],
    'تغذية كيتو': [
      'بيض',
      'لحوم دهنية',
      'جبنة',
      'زبدة',
      'أفوكادو',
      'حلويات كيتو',
      'زيت الزيتون',
      'سمك',
    ],
    'تغذية باليو': [
      'لحم',
      'سمك',
      'خضروات',
      'فواكه',
      'مكسرات',
      'بذور',
      'زيت الزيتون',
      'بطاطا حلوة',
    ],
    'تغذية متوازنة': [
      'منتجات الحبوب الكاملة',
      'دجاج',
      'سمك',
      'خضروات',
      'فواكه',
      'زبادي',
      'بيض',
      'زيوت نباتية',
    ],
    'تغذية خالية من الجلوتين': [
      'أرز',
      'حنطة سوداء',
      'دقيق الذرة',
      'خضروات',
      'فواكه',
      'لحم',
      'سمك',
      'معكرونة خالية من الجلوتين',
    ],
    'تغذية منخفضة الكربوهيدرات': [
      'بيض',
      'صدر الدجاج',
      'سمك',
      'خضروات منخفضة الكربوهيدرات (بروكلي، قرنبيط)',
      'جبنة',
      'أفوكادو',
      'مكسرات',
      'زيت الزيتون',
    ],
    'حمية البحر الأبيض المتوسط': [
      'زيت الزيتون',
      'سمك',
      'مأكولات بحرية',
      'خضروات',
      'فواكه',
      'منتجات الحبوب الكاملة',
      'زبادي يوناني',
      'نبيذ (باعتدال)',
    ],
  },
  es: {
    'Nutrición Deportiva': [
      'batidos de proteína',
      'avena',
      'pechuga de pollo',
      'plátanos',
      'trigo sarraceno',
      'nueces',
      'pescado (salmón, atún)',
    ],
    'Nutrición Dietética': [
      'ensaladas',
      'proteínas magras',
      'verduras',
      'frutas',
      'yogures',
      'queso cottage',
      'trigo sarraceno',
    ],
    'Nutrición Vegetariana': [
      'tofu',
      'aguacate',
      'quinoa',
      'batidos verdes',
      'garbanzos',
      'soja',
      'berenjenas',
      'calabacines',
    ],
    'Nutrición Vegana': [
      'leche vegetal',
      'mantequillas de nueces',
      'tofu',
      'seitán',
      'frijoles',
      'sopas de verduras',
      'frutas',
      'nueces',
    ],
    'Nutrición Keto': [
      'huevos',
      'carnes grasas',
      'queso',
      'mantequilla',
      'aguacate',
      'postres keto',
      'aceite de oliva',
      'pescado',
    ],
    'Nutrición Paleo': [
      'carne',
      'pescado',
      'verduras',
      'frutas',
      'nueces',
      'semillas',
      'aceite de oliva',
      'batata',
    ],
    'Nutrición Equilibrada': [
      'productos de grano entero',
      'pollo',
      'pescado',
      'verduras',
      'frutas',
      'yogures',
      'huevos',
      'aceites vegetales',
    ],
    'Nutrición Sin Gluten': [
      'arroz',
      'trigo sarraceno',
      'harina de maíz',
      'verduras',
      'frutas',
      'carne',
      'pescado',
      'pasta sin gluten',
    ],
    'Nutrición Baja en Carbohidratos': [
      'huevos',
      'pechuga de pollo',
      'pescado',
      'verduras bajas en carbohidratos (brócoli, coliflor)',
      'queso',
      'aguacate',
      'nueces',
      'aceite de oliva',
    ],
    'Dieta Mediterránea': [
      'aceite de oliva',
      'pescado',
      'mariscos',
      'verduras',
      'frutas',
      'productos de grano entero',
      'yogur griego',
      'vino (con moderación)',
    ],
  },
  zh: {
    运动营养: [
      '蛋白质奶昔',
      '燕麦片',
      '鸡胸肉',
      '香蕉',
      '荞麦',
      '坚果',
      '鱼（鲑鱼，金枪鱼）',
    ],
    饮食营养: ['沙拉', '瘦蛋白', '蔬菜', '水果', '酸奶', '奶酪', '荞麦'],
    素食营养: [
      '豆腐',
      '鳄梨',
      '藜麦',
      '绿色冰沙',
      '鹰嘴豆',
      '大豆',
      '茄子',
      '西葫芦',
    ],
    纯素营养: [
      '植物奶',
      '坚果酱',
      '豆腐',
      '麦蛋白',
      '豆类',
      '蔬菜汤',
      '水果',
      '坚果',
    ],
    生酮营养: [
      '鸡蛋',
      '肥肉',
      '奶酪',
      '黄油',
      '鳄梨',
      '生酮甜点',
      '橄榄油',
      '鱼',
    ],
    古饮食: ['肉类', '鱼', '蔬菜', '水果', '坚果', '种子', '橄榄油', '红薯'],
    平衡饮食: [
      '全谷物产品',
      '鸡肉',
      '鱼',
      '蔬菜',
      '水果',
      '酸奶',
      '鸡蛋',
      '植物油',
    ],
    无麸质饮食: [
      '米饭',
      '荞麦',
      '玉米粉',
      '蔬菜',
      '水果',
      '肉类',
      '鱼',
      '无麸质面食',
    ],
    低碳水化合物饮食: [
      '鸡蛋',
      '鸡胸肉',
      '鱼',
      '低碳水化合物蔬菜（西兰花，花椰菜）',
      '奶酪',
      '鳄梨',
      '坚果',
      '橄榄油',
    ],
    地中海饮食: [
      '橄榄油',
      '鱼',
      '海鲜',
      '蔬菜',
      '水果',
      '全谷物产品',
      '希腊酸奶',
      '葡萄酒（适量）',
    ],
  },
  fr: {
    'Nutrition Sportive': [
      'shakes protéinés',
      "flocons d'avoine",
      'poitrine de poulet',
      'bananes',
      'sarrasin',
      'noix',
      'poisson (saumon, thon)',
    ],
    'Nutrition Diététique': [
      'salades',
      'protéines maigres',
      'légumes',
      'fruits',
      'yaourts',
      'fromage cottage',
      'sarrasin',
    ],
    'Nutrition Végétarienne': [
      'tofu',
      'avocat',
      'quinoa',
      'smoothies verts',
      'pois chiches',
      'soja',
      'aubergines',
      'courgettes',
    ],
    'Nutrition Végane': [
      'lait végétal',
      'beurres de noix',
      'tofu',
      'seitan',
      'haricots',
      'soupes de légumes',
      'fruits',
      'noix',
    ],
    'Nutrition Cétogène': [
      'œufs',
      'viandes grasses',
      'fromage',
      'beurre',
      'avocat',
      'desserts cétogènes',
      "huile d'olive",
      'poisson',
    ],
    'Nutrition Paléo': [
      'viande',
      'poisson',
      'légumes',
      'fruits',
      'noix',
      'graines',
      "huile d'olive",
      'patates douces',
    ],
    'Nutrition Équilibrée': [
      'produits céréaliers complets',
      'poulet',
      'poisson',
      'légumes',
      'fruits',
      'yaourts',
      'œufs',
      'huiles végétales',
    ],
    'Nutrition Sans Gluten': [
      'riz',
      'sarrasin',
      'farine de maïs',
      'légumes',
      'fruits',
      'viande',
      'poisson',
      'pâtes sans gluten',
    ],
    'Nutrition Faible en Glucides': [
      'œufs',
      'poitrine de poulet',
      'poisson',
      'légumes à faible teneur en glucides (brocoli, chou-fleur)',
      'fromage',
      'avocat',
      'noix',
      "huile d'olive",
    ],
    'Régime Méditerranéen': [
      "huile d'olive",
      'poisson',
      'fruits de mer',
      'légumes',
      'fruits',
      'produits céréaliers complets',
      'yaourt grec',
      'vin (avec modération)',
    ],
  },
};

export default categories;
